version: '3.9'
services:
  app:
    platform: linux/amd64
    # image: c1a5d4dc904f
    build: .
    ports:
    # host:container
      - 8080:80
    volumes: 
      - ./app2:/app
      - ./models:/app/models
